# Generated by Django 6.0.6 on 2026-06-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("color_hex", models.CharField(default="#A8A77A", max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_pokedex", models.IntegerField(unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("imagen_url", models.URLField(max_length=500)),
                ("hp", models.IntegerField(default=0)),
                ("ataque", models.IntegerField(default=0)),
                ("defensa", models.IntegerField(default=0)),
                ("velocidad", models.IntegerField(default=0)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "tipos",
                    models.ManyToManyField(related_name="pokemones", to="pokemon.tipo"),
                ),
            ],
        ),
    ]
